### ISSUE TITLE
getAccessToken code parameter

### ISSUE THREAD

**Issue by giswebmaster** [coldfumonkeh/GoogleAnalytics#8]
I see the getAccessToken function takes a "code" parameter obtained from the authentication process, but no reference as to where to find this supposed code.  would be handy to have that info to actually use this module

**Comment by coldfumonkeh** [comment]
Have you actually read the README file? it covers where the code value is and what you do next.

https://github.com/coldfumonkeh/GoogleAnalytics/blob/master/README.md

**Comment by giswebmaster** [comment]
this is all I found:
will relocate to the callback URI defined in your app settings with an appended query string parameter, **code**.

apparently this part isn't working for me
